package Hibernate;
// Generated Sep 9, 2012 1:14:55 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Products generated by hbm2java
 */
@Entity
@Table(name="products"
    ,catalog="music_shop"
)
public class Products  implements java.io.Serializable {


     private String model;
     private String brand;
     private String price;

    public Products() {
    }

    public Products(String model, String brand, String price) {
       this.model = model;
       this.brand = brand;
       this.price = price;
    }
   
     @Id 
    
    @Column(name="model", unique=true, nullable=false, length=100)
    public String getModel() {
        return this.model;
    }
    
    public void setModel(String model) {
        this.model = model;
    }
    
    @Column(name="brand", nullable=false, length=100)
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    
    @Column(name="price", nullable=false, length=100)
    public String getPrice() {
        return this.price;
    }
    
    public void setPrice(String price) {
        this.price = price;
    }




}


